-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-3", mode = "preferred", position = "2560x541", scale = 1, vrr = 0 })
hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-5", mode = "1440x900@59.887", position = "1120x0", scale = 1, vrr = 0 })
