-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "DP-3", mode = "1360x768@60.015", position = "1440x1017", scale = 1 })
hl.monitor({ output = "DP-5", mode = "1440x900@59.887", position = "0x479", scale = 1 })
hl.monitor({ output = "eDP-1", disabled = true })
hl.monitor({ output = "DP-4", mode = "1360x768@60.015", position = "1920x479", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-7", mode = "1440x900@59.887", position = "480x0", scale = 1, vrr = 0 })
