[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1d2021"
foreground = "#c5c8c6"

[env]
TERM = "alacritty"

[font]
builtin_box_drawing = true
size = 11.0

[font.normal]
#family = "Fira Code Retina"
#family = "JetBrains Mono"
family = "DejaVu Sans Mono"
style = "Book"

[window]
opacity = 0.85

[window.padding]
x = 8
y = 8

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
