# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

vterm_prompt_end() {                                                                                                          printf "\e]51;A$(whoami)@$(hostname):$(pwd)\e\\";
}
PS1=$PS1'\[$(vterm_prompt_end)\]'


# Put your fun stuff here.
PATH=$PATH:/home/john/scripts:/home/john/.local/bin:/home/john/packages/vault

alias rm="rm -i"
alias mv="mv -i"
alias cp="cp -i"

alias dl="/home/john/scripts/yt-dlp-wrapper.sh"
alias dl-audio="yt-dlp --format m4a/bestaudio --extract-audio --audio-format mp3"
alias dl-tor="yt-dlp --proxy socks5://localhost:9050"
alias dl-jumpbox="yt-dlp --proxy socks5://localhost:9051"
alias curl-tor="curl --proxy socks5://localhost:9050"
alias rs="rsync -avzP"
alias jumpbox-dl="rs jumpbox:/var/lib/transmission/Downloads/* ."
alias kodi-update="ssh pi-master-tv 'kodi-send --action=\"UpdateLibrary(video)\"'"
alias pwgen="tr -dc 'A-Za-z0-9!@#$%^&*()_+-={}[]|:;\",.<>?/' < /dev/urandom | head -c 30; echo"
alias record-audio="ffmpeg -f pulse -i alsa_input.usb-C-Media_Electronics_Inc._USB_Audio_Device-00.mono-fallback out.wav"
alias danger-claude="claude --dangerously-skip-permissions"
export VAULT_ADDR="http://ifd-vault:8200"
export VAULT_TOKEN=$(secret-tool lookup vault token)
export JIRA_BASE_URL="https://infocusdata.atlassian.net"
export JIRA_CLIENT_ID=$(secret-tool lookup jira client_id)
export JIRA_CLIENT_SECRET=$(secret-tool lookup jira client_secret)
export JIRA_REDIRECT_URI=http://localhost:9876/callback
export IFD_FLEET_ROOT=/mnt/crypt/john/projects/the-commodore