# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.
PATH=$PATH:/home/john/scripts

alias dl="/home/john/packages/yt-dlp/yt-dlp.sh"
alias dl-audio="dl --format m4a/bestaudio --extract-audio --audio-format mp3"
alias rs="rsync -avzP"
alias jumpbox-dl="rs jumpbox:/var/lib/transmission/Downloads/* ."
alias kodi-update="ssh pi-master-tv 'kodi-send --action=\"UpdateLibrary(video)\"'"
